development:
  adapter: sqlserver
  dataserver: iaxjlkc5ea.database.windows.net
  database: unite4good-api-db
  username: guestreadonly@iaxjlkc5ea
  password: aCCe$$247
  port: 1433
  azure: true

production:
  adapter: sqlserver
  dataserver: iaxjlkc5ea.database.windows.net
  database: unite4good-api-db
  username: guestreadonly@iaxjlkc5ea
  password: aCCe$$247
  port: 1433
  azure: true